#!/usr/bin/env sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   This is a minimal wrapper script. For full features, regenerate wrapper:
#   ./gradlew wrapper --gradle-version 8.10.2
#
##############################################################################

DIR="$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
JAVA_OPTS="${JAVA_OPTS:-}"

CLASSPATH="$DIR/gradle/wrapper/gradle-wrapper.jar"

if [ -n "$JAVA_HOME" ] ; then
    JAVA_EXE="$JAVA_HOME/bin/java"
else
    JAVA_EXE="java"
fi

exec "$JAVA_EXE" $JAVA_OPTS -Dorg.gradle.appname=gradlew -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"











